### ISSUE TITLE
Metabans Code Needs Updating

### ISSUE THREAD

**Issue by Prophet731** [AdKats/AdKats#779]
You will need to update the metabans code in AdKats to the latest version of the Metabans API.

http://metabans.com/plugin/

```
[02:11:19 49] Metabans API: Received sync response, beginning parse
[02:11:19 49] Metabans API: Response error; Error: unsupported or outdated plugin/client: outdated PRoCon Metabans plugin(1.0.6.0) detected. Get the latest plugin for PRoCon: http://metabans.com/plugin/
[02:11:19 49] Metabans API: Received sync and parse completed
```

**Comment by BP4U** [comment]
Push

**Comment by ColColonCleaner** [comment]
I will work on fixing this shortly.

**Comment by BP4U** [comment]
would be nice, as all german clans ask me why it doesn't work ^^

**Comment by ColColonCleaner** [comment]
This is fixed. Update.

**Comment by BP4U** [comment]
Thx !

**Comment by BP4U** [comment]
sry to say...but still not working

[09:13:52 41] [AdKats] SUCCESS: AdKats 6.6.0.0 startup complete [23s]. Commands are now online.
[09:19:48 93] Metabans API: Post &username=battleplay4u&salt=5f426fda58c135ed17b648cf278b9431d3d9e5b8&apikey=ed445c0d9256ab3979a8df62b0246315c442223c&options=mirror&requests%255B0%255D%255Baction%255D=mb_assess_player&requests%255B0%255D%255Bassessment_length%255D=631152000&requests%255B0%255D%255Bplayer_uid%255D=EA_9A723FD0FC6114B0B36D6D49FA29A312&requests%255B0%255D%255Breason%255D=testban&requests%255B0%255D%255Bassessment_type%255D=black&requests%255B0%255D%255Bgame_name%255D=BF_4
[09:19:49 05] Metabans API: Received sync response, beginning parse
[09:19:49 05] Metabans API: Response error; Error: unsupported or outdated plugin/client: outdated PRoCon Metabans plugin(1.0.6.0) detected. Get the latest plugin for PRoCon: http://metabans.com/plugin/
[09:19:49 05] Metabans API: Received sync and parse completed

**Comment by BP4U** [comment]
"adkats.cs" was not changed, only "adkatsblweaponstats.json" was added

 /// <summary>
            ///     Optional referrer to include in the request header
            /// </summary>
            public string Referrer = "PRoCon Metabans Plugin/1.0.6.0";

            /// <summary>

**Comment by BP4U** [comment]
ok i guess i have to take the test branch

**Comment by BP4U** [comment]
so i took the test branch

i installed 6.7.0.77
it auto auto-updated to 6.6.0.68
then it auto-updated to 6.7.0.77
then it auto-downgraded to 6.6.7.0

result: error occurs again

[13:55:42 51] Metabans API: Post &username=battleplay4u&salt=496c8051de049fc2fb5fc142ce9b0873d724189b&apikey=0031c2e1c0d18bcdce2ebf07977da76a4adbdf96&options=mirror&requests%255B0%255D%255Baction%255D=mb_assess_player&requests%255B0%255D%255Bassessment_length%255D=86280&requests%255B0%255D%255Bplayer_uid%255D=EA_4BE4F03A193BD2F3100C788F7458C203&requests%255B0%255D%255Breason%255D=%2520banned%25201%2520day%2520temp-banned%2520for%2520M67%2520on%2520a%2520no%2520explosives%2520server&requests%255B0%255D%255Bassessment_type%255D=black&requests%255B0%255D%255Bgame_name%255D=BF_4
[13:55:42 65] Metabans API: Received sync response, beginning parse
[13:55:42 65] Metabans API: Response error; Error: unsupported or outdated plugin/client: outdated PRoCon Metabans plugin(1.0.6.0) detected. Get the latest plugin for PRoCon: http://metabans.com/plugin/

**Comment by ColColonCleaner** [comment]
i...what. 6.6.7.0 cannot be updated/downgraded to, it does not exist on the repo anymore. This could have been manual.

**Comment by BP4U** [comment]
ok, thx

**Comment by BP4U** [comment]
![adkats](https://cloud.githubusercontent.com/assets/3889930/8565711/6270e6dc-2558-11e5-800d-a1fa952858b3.png)
